"""add_new_fields_to_employee_model

Revision ID: 2ed141067500
Revises: 31c20ee7cb1f
Create Date: 2025-08-29 13:00:39.699604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed141067500'
down_revision = '31c20ee7cb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('corporate_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('appointment_name', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['corporate_email'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('appointment_name')
        batch_op.drop_column('job_title')
        batch_op.drop_column('qualification')
        batch_op.drop_column('corporate_email')
        batch_op.drop_column('username')
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
