"""Add employment_type to Employee model

Revision ID: 31c20ee7cb1f
Revises: 58cb55dde467
Create Date: 2025-08-29 11:21:36.878744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c20ee7cb1f'
down_revision = '58cb55dde467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('employment_type')

    # ### end Alembic commands ###
