"""Initial migration

Revision ID: 58cb55dde467
Revises: 8641c29ee8f8
Create Date: 2025-08-28 15:18:52.814653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cb55dde467'
down_revision = '8641c29ee8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('appointment_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_period_start', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('pay_period_end', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('overtime_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('gross_salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('net_salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_range_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('salary_range_max', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salary_range_max')
        batch_op.drop_column('salary_range_min')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.alter_column('net_salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('gross_salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('bonus')
        batch_op.drop_column('overtime_pay')
        batch_op.drop_column('pay_period_end')
        batch_op.drop_column('pay_period_start')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('appointment_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
