"""Add new fields to Employee model

Revision ID: 8641c29ee8f8
Revises: 
Create Date: 2025-08-28 11:36:29.698482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8641c29ee8f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=50), nullable=True))
        batch_op.drop_column('hire_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hire_date', sa.DATE(), nullable=False))
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('image_path')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('address')
        batch_op.drop_column('appointment_date')

    # ### end Alembic commands ###
